### ISSUE TITLE
Uncaught Error: Cannot find module 'fixmyjs'

### ISSUE THREAD

**Issue by benhalverson** [sindresorhus/atom-fixmyjs#10]
1. ...Settings → Packages → Search for fixmyjs
2. ...Press install

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.2
**Thrown From**: [fixmyjs](https://github.com/sindresorhus/atom-fixmyjs) package, v1.3.2

### Stack Trace

Uncaught Error: Cannot find module 'fixmyjs'

```
At module.js:330

Error: Cannot find module 'fixmyjs'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/benhalverson/.atom/packages/fixmyjs/index.js:2:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:691:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:239:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:414:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:323:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -6:14.3.0 core:copy (atom-text-editor.editor)
     -6:11.9.0 editor:select-to-end-of-line (atom-text-editor.editor)
     -6:10.6.0 pane:show-next-item (atom-text-editor.editor)
     -6:09.7.0 core:move-up (atom-text-editor.editor)
 11x -6:09.2.0 core:move-left (atom-text-editor.editor)
     -6:07.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -6:07.1.0 editor:newline (atom-text-editor.editor)
     -6:06.7.0 core:move-up (atom-text-editor.editor)
     -6:06.4.0 core:paste (atom-text-editor.editor)
  5x -6:04.0 pane:show-next-item (atom-text-editor.editor)
  5x -6:00.1.0 pane:show-previous-item (atom-text-editor.editor)
     -5:56.9.0 core:save (atom-text-editor.editor)
     -5:56 pane:show-previous-item (atom-text-editor.editor)
     -5:54.7.0 core:save (atom-text-editor.editor)
     -5:53.2.0 core:move-down (atom-text-editor.editor)
     -0:16.8.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.1.0
atom-pair, v1.1.3
atom-typescript, v2.15.2
autocomplete-css, v0.6.0
autocomplete-plus, v2.8.0
autocomplete-plus-python-jedi, v0.2.3
autocomplete-ruby, v0.0.1
color-picker, v1.5.0
emmet, v2.3.7
icon-font-picker, v0.0.1
language-typescript, v0.15.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-less, v0.3.1
npm-autocomplete, v0.1.2
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by kevva** [comment]
https://github.com/sindresorhus/atom-fixmyjs/issues/7 https://github.com/sindresorhus/atom-fixmyjs/issues/9

**Comment by kristianmandrup** [comment]
Got the same error, `Cannot find module 'fixmyjs'`. Any suggestions?

**Comment by jdheeter** [comment]
Same error, just installed today.
