### ISSUE TITLE
Started getting Failed to activate package named 'fixmyjs' Error: Cannot find module 'fixmyjs'

### ISSUE THREAD

**Issue by StevenACoffman** [sindresorhus/atom-fixmyjs#7]
Although this used to work for me (and be awesome), it has stopped working recently. I tried uninstalling it and reinstalling it, but no dice. I globally installed fixmyjs via npm, and although I can not run it on the command line, I still can't use the Atom version. I'm not sure if something else I installed messed it up, or what.

```
Failed to activate package named 'fixmyjs' Error: Cannot find module 'fixmyjs'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/gears/.atom/packages/fixmyjs/index.js:2:15)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:623:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:250:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:232:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:682:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:224:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:336:21)
  at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:140:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
```

**Comment by sindresorhus** [comment]
Looks like an npm install failure where the `fixmyjs` dependency doesn't get installed. I can reproduce this too. But if I go to `~/.atom/packages/fixmyjs` and run `npm install` manually it works.

Open a ticket on https://github.com/atom/atom as this isn't really specific to this package.

**Comment by gaurav21r** [comment]
@sindresorhus Can you please point me to the correct URL in windows? I am just getting a file `atom-1.0.2-delta.nupkg`.

**Comment by kristianmandrup** [comment]
Perhaps mention this work around in the Install section of the README ;)

**Comment by cliffordfajardo** [comment]
@sindresorhus - thanks that worked.

**Comment by garrows** [comment]
FYI I'm still having this issue with the latest stable atom (`v1.6.0`).
